### ISSUE TITLE
Deploy to Raspberry Pi

### ISSUE THREAD

**Issue by thomasgalliker** [Tharnas/EInkDisplayService#1]
Funny, I was doing something very similar these days. To which Raspberry/Microcontroller do you deploy this project? I couldnt get .NET 5 to run on my Raspberry Pi Zero W.

**Comment by Tharnas** [comment]
Hi Thomas,

Interesting to hear! Im doploying it with docker on an ubuntu server. Im using an esp32 to download the image and display it to an eink display. (waveshare 7.5" black / red 800x480)
